import { PodcastAnalysisResult } from '../types';

/**
 * 将播客分析结果转换为Notion格式的Markdown文档
 */
export const exportToNotionMarkdown = (data: PodcastAnalysisResult): string => {
  let markdown = '';

  // 标题
  markdown += `# ${data.title || 'Podcast Analysis'}\n\n`;

  // 元数据
  markdown += `**Generated on:** ${new Date().toLocaleString()}\n`;
  markdown += `**Type:** ${data.overview?.type || 'Podcast'}\n\n`;
  markdown += '---\n\n';

  // Overview部分
  if (data.overview) {
    markdown += '## 📋 Overview\n\n';
    markdown += `**Participants:** ${data.overview.participants || 'N/A'}\n\n`;
    markdown += `**Core Issue:** ${data.overview.coreIssue || 'N/A'}\n\n`;
    markdown += `**Summary:**\n\n${data.overview.summary || 'N/A'}\n\n`;
    markdown += '---\n\n';
  }

  // Core Conclusions部分
  if (data.coreConclusions && data.coreConclusions.length > 0) {
    markdown += '## 🎯 Core Conclusions\n\n';
    data.coreConclusions.forEach((conclusion, index) => {
      markdown += `### ${index + 1}. ${conclusion.role || 'Conclusion'}\n\n`;
      markdown += `**Point:** ${conclusion.point || 'N/A'}\n\n`;
      markdown += `**Basis:** ${conclusion.basis || 'N/A'}\n\n`;
      if (conclusion.source) {
        markdown += `**Source:** ${conclusion.source}\n\n`;
      }
      markdown += '---\n\n';
    });
  }

  // Topic Blocks部分
  if (data.topicBlocks && data.topicBlocks.length > 0) {
    markdown += '## 📚 Topic Blocks\n\n';
    data.topicBlocks.forEach((block, index) => {
      markdown += `### ${index + 1}. ${block.title || 'Topic'}\n\n`;
      markdown += `**Scope:** ${block.scope || 'N/A'}\n\n`;
      markdown += `**Core View:**\n\n${block.coreView || 'N/A'}\n\n`;
      markdown += '---\n\n';
    });
  }

  // Concepts部分
  if (data.concepts && data.concepts.length > 0) {
    markdown += '## 💡 Key Concepts\n\n';
    data.concepts.forEach((concept, index) => {
      markdown += `### ${index + 1}. ${concept.term || 'Concept'}\n\n`;
      markdown += `**Definition:** ${concept.definition || 'N/A'}\n\n`;
      if (concept.context) {
        markdown += `**Context:** ${concept.context}\n\n`;
      }
      if (concept.source) {
        markdown += `**Source:** ${concept.source}\n\n`;
      }
      if (concept.timestamp) {
        markdown += `**Timestamp:** ${concept.timestamp}\n\n`;
      }
      markdown += '---\n\n';
    });
  }

  // Case Studies部分
  if (data.cases && data.cases.length > 0) {
    markdown += '## 📖 Case Studies\n\n';
    data.cases.forEach((caseStudy, index) => {
      markdown += `### Case ${index + 1}\n\n`;
      markdown += `**Story:**\n\n${caseStudy.story || 'N/A'}\n\n`;
      markdown += `**Proves Point:** ${caseStudy.provesPoint || 'N/A'}\n\n`;
      if (caseStudy.source) {
        markdown += `**Source:** ${caseStudy.source}\n\n`;
      }
      markdown += '---\n\n';
    });
  }

  // Actionable Advice部分
  if (data.actionableAdvice && data.actionableAdvice.length > 0) {
    markdown += '## ✅ Actionable Advice\n\n';
    data.actionableAdvice.forEach((advice, index) => {
      markdown += `${index + 1}. ${advice}\n\n`;
    });
    markdown += '---\n\n';
  }

  // Critical Review部分
  if (data.criticalReview) {
    markdown += '## 🔍 Critical Review\n\n';
    markdown += `${data.criticalReview}\n\n`;
    markdown += '---\n\n';
  }

  // Transcript部分（可选，如果存在）
  if (data.transcript) {
    markdown += '## 📝 Transcript\n\n';
    markdown += '<details>\n<summary>Click to expand transcript</summary>\n\n';
    markdown += '```\n';
    markdown += data.transcript;
    markdown += '\n```\n\n';
    markdown += '</details>\n\n';
  }

  // Footer
  markdown += '---\n\n';
  markdown += `*Generated by Podcast Insight AI on ${new Date().toLocaleString()}*\n`;

  return markdown;
};

/**
 * 下载Markdown文件
 */
export const downloadMarkdown = (markdown: string, filename: string): void => {
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

